name: OpenDCS Build and unit tests
on:
  pull_request:
    branches: ["7.1"]
  push:
    branches: ["7.1"]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest,macos-latest,windows-latest]
    runs-on: ${{matrix.platform}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: adopt
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Compile test and stage
        run: |          
          ant test
          ant opendcs